package com.example.jormun_map.Config;

public enum TablesColumn {
    COL_USERINFO_IDUSER("IDUSER",0),
    COL_USERINFO_USERNAME("USERNAME",1),
    COL_USERINFO_TOKEN("TOKEN",2),

    COL_WORLDMAPMIN_IDPOINT("IDPOINT",3),
    COL_WORLDMAPMIN_POINTLAT("POINTLAT",4),
    COL_WORLDMAPMIN_POINTLONG("POINTLONG",5),
    COL_WORLDMAPMIN_OBJECTREF("OBJECTREF",6),
    COL_WORLDMAPMIN_IDREF("IDREF",7),
    COL_WORLDMAPMIN_IDOLDREF("IDOLDREF",8),
    COL_WORLDMAPMIN_TOKENREF("TOKENREF",9),
    COL_WORLDMAPMIN_IDUSER("IDUSER",10),
    COL_WORLDMAPMIN_ELEMENTKEY("ELEMENTKEY",11),

    COL_CURRENTTEAM_IDMEMBER("IDMEMBER",12),
    COL_CURRENTTEAM_IDUSER("IDUSER",13),
    COL_CURRENTTEAM_PATHJSON("PATHJSON",14),
    COL_CURRENTTEAM_IDREL("IDREL",15),

    COL_HERO_IDHERO("IDHERO",16),
    COL_HERO_IDUSER("IDUSER",17),
    COL_HERO_PATHJSON("PATHJSON",18),
    COL_HERO_IDREL("IDREL",19),

    COL_INVENTORY_IDINVENTORY("IDINVENTORY",20),
    COL_INVENTORY_PATHJSON("PATHJSON",21),
    COL_INVENTORY_IDHERO("IDHERO",22),
    COL_INVENTORY_IDREL("IDREL",23),

    COL_ITEM_IDITEM("IDITEM",24),
    COL_ITEM_PATHJSON("PATHJSON",25),
    COL_ITEM_IDINVENTORY("IDINVENTORY",26),
    COL_ITEM_IDREL("IDREL",27),

    COL_MONSTER_IDMONSTER("IDMONSTER",28),
    COL_MONSTER_PATHJSON("PATHJSON",29),
    COL_MONSTER_IDUSER("IDUSER",30),
    COL_MONSTER_IDREL("IDREL",31),

    COL_VILLAGE_IDVILLAGE("IDVILLAGE",32),
    COL_VILLAGE_PATHJSON("PATHJSON",33),
    COL_VILLAGE_IDUSER("IDUSER",34),
    COL_VILLAGE_IDREL("IDREL",35),

    COL_STRUCTURE_IDSTRUCTURE("IDSTRUCTURE",36),
    COL_STRUCTURE_PATHJSON("PATHJSON",37),
    COL_STRUCTURE_IDUSER("IDUSER",38),
    COL_STRUCTURE_IDREL("IDREL",39),

    COL_BUILDING_IDBUILDING("IDBUILDING",40),
    COL_BUILDING_PATHJSON("PATHJSON",41),
    COL_BUILDING_IDVILLAGE("IDVILLAGE",42),
    COL_BUILDING_IDREL("IDREL",43),

    COL_QUEST_IDQUEST("IDQUEST",44),
    COL_QUEST_PATHJSON("PATHJSON",45),
    COL_QUEST_TOKEN("TOKEN",46),
    COL_QUEST_IDREL("IDREL",47),

    COL_BOSS_IDBOSS("IDBOSS",48),
    COL_BOSS_PATHJSON("PATHJSON",49),
    COL_BOSS_IDREL("IDREL",50),

    COL_RESSOURCEZONE_IDZONE("IDZONE",51),
    COL_RESSOURCEZONE_PATHJSON("PATHJSON",52),
    COL_RESSOURCEZONE_IDREL("IDREL",53);


    private final String sValue;
    private final int iValue;

    TablesColumn(String sValue, int iIndex) {
        this.sValue = sValue;
        this.iValue = iIndex;
    }

    @Override
    public String toString() {
        return sValue;
    }
}
