package com.example.jormun_map.Config;

public enum TablesColumn {
    COL_INFOUSER_IDUSER("IDUSER",0),
    COL_INFOUSER_USERNAME("USERNAME",1),
    COL_INFOUSER_TOKEN("TOKEN",2),

    COL_WORLDMAPMIN_IDPOINT("IDPOINT",3),
    COL_WORLDMAPMIN_POINTLAT("POINTLAT",4),
    COL_WORLDMAPMIN_POINTLONG("POINTLONG",5),
    COL_WORLDMAPMIN_OBJECTREF("OBJECTREF",6),
    COL_WORLDMAPMIN_IDREF("IDREF",7),
    COL_WORLDMAPMIN_IDOLDREF("IDOLDREF",8),
    COL_WORLDMAPMIN_TOKENREF("TOKENREF",9),
    COL_WORLDMAPMIN_ELEMENTKEY("ELEMENTKEY",10),

    COL_CURRENTTEAM_IDMEMBER("IDMEMBER",11),
    COL_CURRENTTEAM_IDUSER("IDUSER",12),
    COL_CURRENTTEAM_PATHJSON("PATHJSON",13),

    COL_HERO_IDHERO("IDHERO",14),
    COL_HERO_IDUSER("IDUSER",15),
    COL_HERO_PATHJSON("PATHJSON",16),

    COL_INVENTORY_IDINVENTORY("IDINVENTORY",17),
    COL_INVENTORY_PATHJSON("PATHJSON",18),
    COL_INVENTORY_IDHERO("IDHERO",19),

    COL_ITEM_IDITEM("IDITEM",20),
    COL_ITEM_PATHJSON("PATHJSON",21),
    COL_ITEM_IDINVENTORY("IDINVENTORY",22),

    COL_MONSTER_IDMONSTER("IDMONSTER",23),
    COL_MONSTER_PATHJSON("PATHJSON",24),
    COL_MONSTER_IDUSER("IDUSER",25),

    COL_VILLAGE_IDVILLAGE("IDVILLAGE",26),
    COL_VILLAGE_PATHJSON("PATHJSON",27),
    COL_VILLAGE_IDUSER("IDUSER",28),

    COL_STRUCTURE_IDSTRUCTURE("IDSTRUCTURE",29),
    COL_STRUCTURE_PATHJSON("PATHJSON",30),
    COL_STRUCTURE_IDUSER("IDUSER",31),

    COL_BUILDING_IDBUILDING("IDBUILDING",32),
    COL_BUILDING_PATHJSON("PATHJSON",33),
    COL_BUILDING_IDVILLAGE("IDVILLAGE",34),

    COL_QUEST_IDQUEST("IDQUEST",35),
    COL_QUEST_PATHJSON("PATHJSON",36),
    COL_QUEST_TOKEN("TOKEN",37);

    private final String sValue;
    private final int iValue;

    TablesColumn(String sValue, int iIndex) {
        this.sValue = sValue;
        this.iValue = iIndex;
    }

    @Override
    public String toString() {
        return sValue;
    }
}
